directories:
  output: dist
  buildResources: build
publish:
  - provider: github
    owner: jynng
    repo: kjhsahdhhwkak
    token: <stripped sensitive data>
appId: com.moovix.app
productName: Moovix
win:
  target: nsis
  icon: build/icon.ico
electronVersion: 1.8.8
